### ISSUE TITLE
Investigate Redis connection issues

### ISSUE THREAD

**Issue by shalvah** [shalvah/DownloadThisVideo#11]
This error was observed at 03:04:39 on 20 March 2019:

> ERR max number of clients reached

Around that time, AWS Lambda says there were 309 concurrent invocations. (a local maximum, but not the highest that day). The Redis instance logs show no unusual activity.

This can probably be mitigated by using connection pooling (which is not trivial to implement in a serverless environment.

**Comment by shalvah** [comment]
Interesting read - https://spotinst.com/blog/2017/11/19/best-practices-serverless-connection-pooling-database/

**Comment by dentarg** [comment]
You could use a proxy, e.g. https://github.com/twitter/twemproxy, their README says

>It was built primarily to reduce the number of connections to the caching servers on the backend.

Not sure where to run the proxy though in a serverless environment 🤔 😄

**Comment by shalvah** [comment]
Never mind, I solved this. Switched to a shared cache connection and
prevented the Lambda function from waiting for the connection to close
before exiting

**Comment by shalvah** [comment]
Never mind, I solved this by switching to a shared cache connection and preventing the Lambda function from waiting for the connection to close before exiting. Now the connection is only dependent on the number of fresh instances running simultaneously, which is almost always within our limit of 256 connections.
