### ISSUE TITLE
Twitter livestream vids aren't downloadable

### ISSUE THREAD

**Issue by oldcityws** [shalvah/DownloadThisVideo#12]
Does not work on this live broadcast that was made on the Twitter app: https://twitter.com/amybarnes_usa/status/1119078666552664067

**Comment by shalvah** [comment]
Thanks for reporting. Checked out the Tweet in question. This is what Twitter reports for it:

```
"entities":{"hashtags":[],"symbols":[],"user_mentions":[],"urls":[{"url":"https://t.co/kjAFvYQNO8","expanded_url":"https://twitter.com/i/broadcasts/1OdKrvlZooYKX","display_url":"twitter.com/i/broadcasts/1…","indices":[48,71]}]},"source":"<a href=\"https://periscope.tv\" rel=\"nofollow\">Periscope</a>"
```

Right now, I can't think of an easy way to retrieve media URLs for broadcasts. Broadcasts are not supported on non-JS browsers even, so that's not doable.
