### ISSUE TITLE
PWA support

### ISSUE THREAD

**Issue by Youngestdev** [shalvah/DownloadThisVideo#13]
Hi Shalvah, I was thinking instead of opening the browser every time, wouldn't it be nice if the web app is made an installable PWA?

**Comment by shalvah** [comment]
Hi @Youngestdev , I'm no longer doing any non -essential active development on this project, so, sorry, that's going to be a no. 🙂Btw, the website uses web push notifications, and that's as close as I'm willing to get to a PWA. Anyone who doesn't want to have to navigate in a browser can use their browser's "Add to Home" functionality.

**Comment by Youngestdev** [comment]
Kk, gotcha. Thanks.
