### ISSUE TITLE
Automated replies don't show up under the tweet and in notifications

### ISSUE THREAD

**Issue by shalvah** [shalvah/DownloadThisVideo#2]
Even though the bot has replied to a tweet (and the reply count reflects this), the reply does not show up when you click on the tweet, neither is a notification dispatched. The only way to view the reply is if you're following the bot, in which case it shows up on your timeline.

**Comment by shalvah** [comment]
Preliminary guess would be something to do with how the reply is constructed. Worth looking into the values of `in_reply_to_user_id_str`, `in_reply_to_status_id_str`, `in_reply_to_user_id`,  `in_reply_to_status_id`, and `in_reply_to_screen_name` parameters in the returned object. Currently, the bot uses the `in_reply_to_status_id` parameter in conjuction with mentioning the requesting user in the text, as described here:

![image](https://user-images.githubusercontent.com/14361073/44672944-f40dfc00-aa21-11e8-956a-abc387e8f6a3.png)

It would probably be worth trying `auto_populate_reply_metadata`. (See https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-statuses-update)

Alternatively, this may be a kind of shadow ban, in which case we can't really do anything about it. Hopefully it's not.

**Comment by Akamaozu** [comment]
Sounds like shadow ban, bro.

http://jimkang.com/weblog/articles/twitter-bot-hellban/

**Comment by shalvah** [comment]
I'm actually not sure it is. It only happens sometimes. And, fortunately, recently, it's happened much less, I think.

**Comment by Akamaozu** [comment]
It always happens for me.  Maybe you can see it because you're following the bot and the requester? Or vice versa?

Either way I've never seen it work properly :'(

**Comment by shalvah** [comment]
Ah. Lool. Sorry. Honestly no idea. I see the notification for responses to my tweets. 
Try un-checking the "Quality filter" option in your Twitter notifications.🤷‍♂️

**Comment by Akamaozu** [comment]
No filters on my twitter feed. No blocked individuals and I don't believe I have any muted words.

**Comment by bellarodrz** [comment]
How do I download the video 😃

**Comment by Jolaolu** [comment]
> How do I download the video

 Visit http://download-this.video/your-Twitter-handle
