### ISSUE TITLE
Add favicon and Title to /beta/USERNAME

### ISSUE THREAD

**Issue by InternalLoss** [shalvah/DownloadThisVideo#8]
Currently, /beta/USERNAME doesn't show any <title>, instead just a URL - this may be confusing for some users, and showing something like "This_Vid - @USERNAME" might be a better idea. Furthermore, no favicon is included, which means in some browsers the site might look slightly off.

I completely understand that these are pedantic issues and I completely understand if you close the issue, it'd just be nicer as formatting :wink:

**Comment by shalvah** [comment]
Oh sure, I'll get to it. Thanks.

**Comment by shalvah** [comment]
Done in 991680dba230e4d31f2bea45c031fa16cd5e4e9f and b2c96eb044dd364d7c4c14d302477429559efaa0
